"""Deterministic scene-intent classification and query expansion.

Why this exists: the real observed failure is that too many scenes fall
back to text-only information cards. One real, free (no extra Gemini
call) lever to fix that is to give asset_acquisition.py's search step a
BIGGER, more targeted pool of candidates to choose from before Vision ever
looks at anything -- more relevant hits in the pool means a better chance
one of them is honestly a strong match. `classify_scene_intent()` looks at
a scene's own narration/on-screen text/queries (already generated by
Script Agent, no new LLM call) and buckets it into one of a handful of
recurring shot intents for this niche; `expand_queries_for_intent()` then
adds a few generic, deterministic, provider-friendly query phrases for
that bucket ON TOP OF (never replacing) Script Agent's own queries, so an
early-stopping `_collect_candidates()` loop (see asset_acquisition.py) is
more likely to find something real fast.

This module never talks to Pexels/Pixabay/Gemini itself -- it only
produces classification labels and plain query strings.
"""

from __future__ import annotations

from scripts.production.models import Scene

HARDWARE_DETAIL = "hardware_detail"
PC_SETUP = "pc_setup"
MONITOR_UI = "monitor_ui"
PERSON_USE_CASE = "person_use_case"
SHOPPING_BUYING = "shopping_buying"
OPTIMIZATION_SETTINGS = "optimization_settings"
ABSTRACT_TECH = "abstract_tech"

# Order matters: checked top-to-bottom, first keyword-overlap winner takes
# it (see classify_scene_intent) -- more specific intents (shopping,
# optimization) are listed before the more generic hardware/setup ones so a
# scene that is clearly about buying/optimizing isn't miscategorized just
# because it also mentions a hardware noun in passing.
_INTENT_KEYWORDS: list[tuple[str, set[str]]] = [
    (
        SHOPPING_BUYING,
        {"buy", "buying", "shop", "shopping", "store", "price", "priced", "deal", "deals",
         "discount", "discounts", "purchase", "sale", "compare", "comparing", "comparison", "review", "worth"},
    ),
    (
        OPTIMIZATION_SETTINGS,
        {"optimize", "optimizing", "optimization", "settings", "setting", "tweak", "tweaking",
         "configure", "boost", "fps", "performance", "overclock", "overclocking", "tuning"},
    ),
    (
        MONITOR_UI,
        {"screen", "monitor", "display", "ui", "menu", "interface", "resolution", "refresh", "software", "app"},
    ),
    (
        PERSON_USE_CASE,
        {"person", "hand", "hands", "typing", "playing", "gamer", "player", "unboxing", "unbox", "reacting"},
    ),
    (
        HARDWARE_DETAIL,
        {"gpu", "cpu", "graphics", "card", "processor", "ram", "memory", "ssd", "storage",
         "motherboard", "cooler", "cooling", "psu", "component", "chip", "inside", "case", "build"},
    ),
    (
        PC_SETUP,
        {"setup", "desk", "rig", "workstation", "room", "environment", "workspace"},
    ),
]

DEFAULT_INTENT = ABSTRACT_TECH

# Generic, honest, provider-friendly phrases per intent -- deliberately
# never naming a specific product/game (see the task's "never imply
# generic stock footage is footage of a specific named game/GPU/laptop/
# product" rule, unchanged from Script Agent's own query-generation rule).
# These only ever ADD to Script Agent's own scene-specific queries, never
# replace them.
_INTENT_QUERY_TEMPLATES: dict[str, list[str]] = {
    HARDWARE_DETAIL: [
        "computer hardware close up",
        "PC component macro shot",
        "gpu installed in pc case close up",
    ],
    PC_SETUP: [
        "gaming desk setup",
        "PC build on desk",
        "gaming room setup wide shot",
    ],
    MONITOR_UI: [
        "gaming monitor screen close up",
        "computer settings menu on screen",
        "PC display user interface",
    ],
    PERSON_USE_CASE: [
        "person using gaming pc",
        "hands typing on keyboard",
        "gamer sitting at desk",
    ],
    SHOPPING_BUYING: [
        "person shopping for computer parts",
        "comparing computer hardware in store",
        "online shopping for pc parts on laptop",
    ],
    OPTIMIZATION_SETTINGS: [
        "pc performance settings menu",
        "adjusting game graphics settings",
        "computer optimization software screen",
    ],
    ABSTRACT_TECH: [
        "computer technology background",
        "digital technology abstract",
        "circuit board close up",
    ],
}

MAX_QUERIES_PER_SCENE = 8


def classify_scene_intent(scene: Scene) -> str:
    """Buckets a scene into one recurring shot intent for this niche, using
    only text already on the Scene (narration, on-screen text, Script
    Agent's own queries) -- no new LLM call."""
    text_parts = [scene.narration_line, scene.on_screen_text or "", *scene.visual_search_queries]
    combined = " ".join(text_parts).lower()
    words = set(_tokenize(combined))

    best_intent = DEFAULT_INTENT
    best_overlap = 0
    for intent, keywords in _INTENT_KEYWORDS:
        overlap = len(words & keywords)
        if overlap > best_overlap:
            best_overlap = overlap
            best_intent = intent
    return best_intent


def _tokenize(text: str) -> list[str]:
    return [word.strip(".,!?:;\"'()") for word in text.split()]


def expand_queries_for_intent(intent: str, existing_queries: list[str]) -> list[str]:
    """Returns `existing_queries` plus a few deterministic, generic query
    phrases for `intent` -- deduplicated (case-insensitive), existing
    queries always kept and always listed first, capped at
    MAX_QUERIES_PER_SCENE total so this can never balloon provider call
    volume."""
    combined = list(existing_queries)
    seen = {query.strip().lower() for query in combined}
    for candidate in _INTENT_QUERY_TEMPLATES.get(intent, _INTENT_QUERY_TEMPLATES[ABSTRACT_TECH]):
        key = candidate.strip().lower()
        if key in seen:
            continue
        combined.append(candidate)
        seen.add(key)
        if len(combined) >= MAX_QUERIES_PER_SCENE:
            break
    return combined[:MAX_QUERIES_PER_SCENE]


def effective_queries_for_scene(scene: Scene) -> list[str]:
    """The actual query list asset_acquisition.py should search with: the
    scene's own Script-Agent-generated queries (or, defensively, its
    narration line if Script Agent somehow produced none) expanded with a
    few intent-appropriate generic phrases."""
    base_queries = scene.visual_search_queries or [scene.narration_line]
    intent = classify_scene_intent(scene)
    return expand_queries_for_intent(intent, base_queries)
